### ISSUE TITLE
Library timeout

### ISSUE THREAD

**Issue by wojciechprogramista** [mopidy/mopidy-spotify#138] opened 2017-05-03 13:53 UTC
When trying to access my Spotify library, either through `ncmpc` or `ncmpcpp`, I can load my playlist and play music, but I'm unable to access library. After some short period of time, I see the client timeouts. I tried to manipulate caching, timeout and private session settings (just in case), but nothing seems to affect this. This is a fresh mopidy+ncmpcpp installation on Arch and I've never seen it working actually.

Is there anything I could look into? Thanks for help.

**Comment by kingosticks** [comment] 2017-05-05 13:42
This looks to be a duplicate of https://github.com/mopidy/mopidy-spotify/issues/122

**Closed by kingosticks** 2017-05-05 13:42 UTC
