### ISSUE TITLE
fail to login at startup

### ISSUE THREAD

**Issue by mczerski** [mopidy/mopidy-spotify#296] opened 2021-01-02 23:02 UTC
Hi,
I'm using mopidy_spotify v4.0.1 on armbian buster on nano pi NEO SBC. I see there is an issue with spotify login when login fails on mopidy startup. For example, when there is no internet connection at mopidy startup and the internet connection comes back after couple of minutes spotify backend does not try to login again.
To reproduce the issue, the connection must not come back until this log line appears:
```
ERROR [24188:SpotifyEventLoop] spotify.session: Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
```
I have a solution but i'm not sure if this is correct, but at least it solves the problem for me:
```
diff --git a/mopidy_spotify/backend.py b/mopidy_spotify/backend.py
index 7cefb48..e4777dc 100644
--- a/mopidy_spotify/backend.py
+++ b/mopidy_spotify/backend.py
@@ -90,6 +90,16 @@ class SpotifyBackend(pykka.ThreadingActor, backend.Backend):
             self._logged_out,
             backend_actor_proxy,
         )
+        def logged_in(session, error_type):
+            if error_type is spotify.ErrorType.OK:
+                logger.error('Logged in as %s' % session.user)
+            else:
+                logger.error('Login failed: %s' % error_type)
+                session.login(
+                    self._config["spotify"]["username"],
+                    self._config["spotify"]["password"],
+                )
+        session.on(spotify.SessionEvent.LOGGED_IN, logged_in)
         session.on(
             spotify.SessionEvent.PLAY_TOKEN_LOST,
             on_play_token_lost,
```

**Comment by 3nprob** [comment] 2022-06-16 04:03
Looks like duplicate of #259

**Comment by adamcik** [comment] 2022-06-16 05:28
See #110, Spotify turned down the library we used with one months notice...

**Comment by adamcik** [comment] 2022-06-16 05:31
And the fix that is in flight shouldn't have the login issue you describe if I'm not mistaken.

**Comment by 3nprob** [comment] 2022-06-16 05:58
@adamcik The error here looks different from that (ie was still present before the ongoing)

**Comment by adamcik** [comment] 2022-06-16 06:15
That's what I get for looking at this first thing in the morning :P

**Comment by kingosticks** [comment] 2023-03-27 15:39
libspotify has been removed, this issue won't occur in the latest version (but I fully expect one like it might so please reopen if so.

**Closed by kingosticks** 2023-03-27 15:39 UTC
