### ISSUE TITLE
"Failed to load some URI(s)" when I try to play a song

### ISSUE THREAD

**Issue by elmirkouliev** [mopidy/mopidy-spotify#137] opened 2017-04-09 19:17 UTC
I tried entering my spotify creds into the mopidy config and connected directly via the settings page in Iris, but I can't seem to get any of the tracks to play. Anything I'm missing here?

**Comment by fluffywaffles** [comment] 2017-04-20 17:05
For Iris you need mopidy-spotify-web and you have to give mopidy-spotify-web your client id and client secret

**Comment by jaedb** [comment] 2017-04-23 19:48
@elmirkouliev You don't actually need `mopidy-spotify-web`. 

This error can occur in _Iris_ where loading URIs returned no results. Typically this is because said track(s) are not released in your region.

To work around this, try adding your country and locale under the `[iris]` section in `mopidy.conf`. For example:
```
[iris]
enabled = true
country = NZ
locale = en_NZ
```

**Comment by kingosticks** [comment] 2017-05-11 16:38
Is this a mopidy-spotify bug?

**Comment by ABeltramo** [comment] 2017-05-18 10:07
Same problem here. I can see the spotify albums, songs but can't play it. 
Any way we can debug more? Maybe related to [#110](https://github.com/mopidy/mopidy-spotify/issues/110)?

**Comment by kingosticks** [comment] 2017-05-19 13:03
It sounds like this was a usage issue with mopidy-iris i.e. not a bug in mopidy-spotify.  I'm not sure what this has to do with #110, it sounds more like https://github.com/mopidy/mopidy-spotify/issues/97, if anything.

Please post general usage questions at https://discuss.mopidy.com/ rather than this bug tracker.

**Closed by kingosticks** 2017-05-19 13:03 UTC

**Comment by atr0n** [comment] 2017-06-08 22:07
You need to fullfil the client_id and the client_secret in your config file.
More info: https://www.mopidy.com/authenticate/#spotify

**Comment by adamcik** [comment] 2017-06-08 22:15
Locking as this isn't a mopidy-spotify issue and this started well before the OAuth changes on spotify's side.
