### ISSUE TITLE
Spotify stutters on Pi

### ISSUE THREAD

**Issue by woutervanwijk** [mopidy/mopidy-spotify#26] opened 2014-10-06 09:12 UTC
On the Raspberry Pi, including Pi MusicBox, playing music from Spotify sometimes stutters at the start of a track. Not always, but it does. I can see a small short burst of CPU usage when it happens. It does not happen with all files.
Sound does not stutter in the same configuration on any other extension, so this must have something to do with mopidy-spotify. 
I made it stutter less by using a gstreamer cache for the output in the ini file:
output = alsasink buffer-time=200000 latency-time=10000
and setting mopidy to a high nice value (like 15 or 19)

**Comment by jodal** [comment] 2015-01-25 23:57
What's the final conclusion here? Is this still a problem?

**Comment by kingosticks** [comment] 2015-01-27 00:24
Sadly, yes. I upgraded both pyspotify and mopidy-spotify on to the latest github versions on my musicbox install and the problem remains. But, unlike before, the problem doesn't seem to be fixed by setting `cache_dir =`. So, bizarrely it's actually worse. Is there any way that v2.x it's still trying to do the caching? But maybe using some other random directory?

**Comment by jodal** [comment] 2015-01-27 22:59
And the problem is the same with Mopidy-Spotify 1.2.0 and pyspotify 1.x?

`cache_location` in pyspotify defaults to "tmp" in the current working dir if not set. If set to an empty string (or `None` if running pyspotify v2.x/develop) libspotify should not cache to disk at all, AFAIK.

**Comment by kingosticks** [comment] 2015-01-27 22:59
Since this made utterly no sense I've tried it again with a virtualenv for each version and switching between them.  There is certainly an issue with v2 but it might actually be something else. When switching songs in musicbox-webclient and moped, something triggers a few playlist fetches and (for me) these completes in a few seconds, exactly as the song is stuttering at the start.  So maybe just a bug in the webclient. 

I tried switching to using mpd and it was only bad when I ran into https://github.com/mopidy/mopidy/issues/934.

**Comment by kingosticks** [comment] 2015-01-27 23:01
And yes, with Mopidy-Spotify 1.2.0 and pyspotify 1.x and using the cache it stutters a lot at the start on every song.

**Comment by jodal** [comment] 2015-01-27 23:02
OK, so fixing mopidy/mopidy#934 might help for that specific use case, and for the general problem, changing Mopidy's core API to a lot cheaper `library.get_playlists()`, which just returns a list of `Ref.playlist(uri, name)` instead of complete playlists, should stress the Raspi a whole lot less.

**Comment by kingosticks** [comment] 2015-01-27 23:06
Yep, sounds good. 

I'd also like to understand why both the webclients I've tried want to fetch the playlists during track switching. On the face of it I can't see why that would be necessary.

**Comment by machacd** [comment] 2015-02-24 10:48
I also experience this issue, with mopidy on Pi running Arch linux. Any luck resolving it so far?

**Comment by CookieMonger** [comment] 2015-02-25 18:28
Also experiencing this, on Pi2 to a much lesser extent than previously on Pi-B.

**Comment by jodal** [comment] 2015-03-24 14:03
mopidy/mopidy#934 has been fixed and we've updated the playlists provider API in Mopidy 1.0 to use more refs and less complete expensive playlists.

This issue should be retested using latest Mopidy develop (soon to be 1.0) and Mopidy-Spotify develop (soon to be 2.0).

@kingosticks Can you have a new look?

**Comment by jodal** [comment] 2015-05-03 21:30
@kingosticks Did you get around to reproducing this with Mopidy 1.0 and Mopidy-Spotify develop/2.0?

**Comment by kingosticks** [comment] 2015-05-04 16:37
Sorry I didn't get around to this before but the great news is that I cannot reproduce this any more. I've been using Mopidy v1.0.4 and the pyspotify/mopidy-spotify develop branches all day and I think I've heard just one very slight stutter. I've repeatedly tried doing everything that used to make this happen and it's been fine.

**Comment by jodal** [comment] 2015-05-05 06:16
OK, then I'll close this for now with the official explanation that Mopidy 1.0 performance improvements fixed this. Thanks for testing!

**Closed by jodal** 2015-05-05 06:16 UTC
Labels: bug
