### ISSUE TITLE
m3u8 playlists don't fetch metadata

### ISSUE THREAD

**Issue by ldelelis** [mopidy/mopidy-spotify#141] opened 2017-05-09 23:55 UTC
At the moment of loading a .m3u8 playlist through any client, the only thing that gets loaded is the track name. Time, album and artist all show as undefined.
Here's my mopidy.conf:

```
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
restore_state = true

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
data_dir = /var/lib/mopidy/local
media_dir = /var/lib/mopidy/media

[m3u]
playlists_dir = /var/lib/mopidy/playlists
default_encoding = utf-8 
default_extension = .m3u8

[spotify]
username = *myuser*
password = *mypassword*
bitrate = 320
allow_playlists = true
```

Loading playlists created from Spotify fetch their metadata just fine. Adding a track to an .m3u8 playlists fetchs it too, but after restarting mopidy and reloading the playlist it's gone.

**Comment by kingosticks** [comment] 2017-05-10 09:47
This behaviour is true for all backends as m3u playlist support is part of mopidy, not mopidy-spotify. It's also by design that [PlaylistsController.get_items()](https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaylistsController.get_items) returns `Refs` (name and URI) and not `Tracks` (full metadata). It's up the frontend to do the lookups and obtain the full track metadata when it needs the full data. Mopidy-Musicbox-webclient does just this.

**Comment by ldelelis** [comment] 2017-05-10 22:28
You we're right to presume I didn't test it, since I'd prefer to stick to command line clients. Is there anything that I could change to the method you mentioned so it returns `Tracks` instead of `Refs`? Because, even if I do switch to a web client such as Musicbox, my polybar module still returns tracks with "untitled artist".

**Comment by kingosticks** [comment] 2017-05-11 08:40
So what frontend are you actually using? MPD?

**Comment by kingosticks** [comment] 2017-05-11 08:59
Looks like you are. This is https://github.com/mopidy/mopidy/issues/1511 so I'm closing this here in favour of that discussion which is much further along.

**Closed by kingosticks** 2017-05-11 08:59 UTC
