### ISSUE TITLE
Can't find certain artist using mopidy-spotify 

### ISSUE THREAD

**Issue by Jorick** [mopidy/mopidy-spotify#106] opened 2016-06-22 15:44 UTC
I can't find the artist "The black box revelation" wen I use mopidy-spotify. 
Searching them with the Android app, or the Spotify webplayer works fine. So they are on Spotify.

I tried searching both with ncmpcpp en gmpc as frontends.
Searching for this band worked fine before the switch to the web api. I just haven't gotten around to report it.

I ran mopidy with the verbose flag enabled but it showed no errors.

**Comment by PJkeeh** [comment] 2016-07-27 08:24
Same here, also some albums are gone.

**Comment by kingosticks** [comment] 2016-07-27 15:13
In the case of @Jorick's "The black box revelation" this seems to be related to the Web API's `market` query parameter. We currently don't specify this parameter and apparently the default is 'US' where I guess the artist is not available on Spotify:
* [No market](https://api.spotify.com/v1/search?q=%22The+black+box+revelation%22&limit=50&type=album%2Cartist%2Ctrack) - 0 results
* [US market](https://api.spotify.com/v1/search?q=%22The+black+box+revelation%22&limit=50&type=album%2Cartist%2Ctrack&market=US) - 0 results
* [GB market](https://api.spotify.com/v1/search?q=%22The+black+box+revelation%22&limit=50&type=album%2Cartist%2Ctrack&market=GB) - many results!

This is fixed in https://github.com/mopidy/mopidy-spotify/pull/109 which just needs a bit of tidying up.

**Comment by PJkeeh** [comment] 2016-08-01 08:19
Can't wait

**Comment by Jorick** [comment] 2016-08-02 19:06
Sweet, thanks!

**Comment by kingosticks** [comment] 2017-02-01 12:14
Closing as this is really just a duplicate of https://github.com/mopidy/mopidy-spotify/issues/97. #109 was never merged but it looks like we won't want to fix it that way anyway.

**Closed by kingosticks** 2017-02-01 12:14 UTC
