### ISSUE TITLE
unable to use

### ISSUE THREAD

**Issue by EduardVidalTulsa** [mopidy/mopidy-spotify#90] opened 2016-02-04 10:44 UTC
I have installed pip, whit these packages
pip list
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
cachetools (1.1.5)
certifi (2015.11.20.1)
cffi (1.5.0)
configobj (5.0.6)
ipaddress (1.0.16)
javapackages (4.1.0)
Jinja2 (2.8)
lxml (3.3.6)
MarkupSafe (0.23)
Mopidy (1.1.2)
Mopidy-InternetArchive (2.0.0)
Mopidy-Mopify (1.5.14)
Mopidy-MusicBox-Webclient (1.0.3)
Mopidy-Spotify (2.2.0)
Mopidy-Spotify-Tunigo (0.2.1)
Mopidy-WebSettings (0.1.4.2)
Mopidy-Youtube (2.0.2)
net-monitor (0.20)
numpy (1.8.2)
pafy (0.4.3)
pip (8.0.2)
pycparser (2.14)
pycurl (7.19.5)
pygobject (3.14.0)
Pykka (1.2.1)
pyspotify (2.0.5)
PyXB (1.2.3)
requests (2.9.1)
setuptools (19.7)
simplejson (3.6.3)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.3)
tunigo (0.1.3)
uritools (1.0.1)
youtube-dl (2016.2.1)
in my [spotify] settings for mopidy have that
[spotify]
enabled=true
username = myusername
password = ******
I install libspotify.so.12 on /usr/local has manual instalation for these lib says 
But when i start mopidy say that
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Starting Mopidy 1.1.2
INFO     Loading config from builtin defaults
INFO     Loading config from /home/festuc/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, spotify, mpd, http, stream, spotify_tunigo, m3u, youtube, internetarchive, softwaremixer, file, musicbox_webclient, websettings, local
INFO     Disabled extensions: none
ERROR    Extension spotify failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 145, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/__init__.py", line 49, in setup
    from mopidy_spotify.backend import SpotifyBackend
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 11, in <module>
    import spotify
  File "/usr/lib64/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: libspotify.so.12: no s’ha pogut obrir el fitxer objecte compartit: El fitxer o directori no existeix
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: InternetArchiveBackend, YouTubeBackend, SpotifyTunigoBackend, StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Loaded 0 M3U playlists from /home/festuc/.local/share/mopidy/m3u
INFO     Audio output set to "autoaudiosink"
INFO     No local library metadata cache found at /home/festuc/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.                                                    
INFO     Loaded 0 local tracks using json                                        
INFO     Starting Mopidy core                                                    
INFO     Starting Mopidy frontends: QueueManagerFrontend, MpdFrontend, HttpFrontend                                                                               
INFO     MPD server running at [::ffff:127.0.0.1]:6600                           
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
Any idea?
I'm in mageia 5

**Comment by trygveaa** [comment] 2016-02-04 11:32
It was a bit hard to read this since there is no formatting, but it looks like the error is that pyspotify can't find libspotify. The libspotify library has to be placed in a directory that is in your library path. This includes `/lib`, `/usr/lib` and the directories listed in `/etc/ld.so.conf`. You have probably placed libspotify in another directory. Note that `/usr/local/lib` is not on the library path in all distributions.

To check which directories and libraries are found, run `ldconfig -v`. Move libspotify to one of the directories listed there, or add the directory you have put it in to `/etc/ld.so.conf` and run `ldconfig`.

This is not a bug with Mopidy-Spotify, so I'm closing this issue. As per our [issue guidelines](https://docs.mopidy.com/en/latest/contributing/#issue-guidelines), please post to https://discuss.mopidy.com/ if you need further help.

**Closed by trygveaa** 2016-02-04 11:32 UTC
