### ISSUE TITLE
Timeout: Operation did not complete in 10.000s

### ISSUE THREAD

**Issue by gspray** [mopidy/mopidy-spotify#78] opened 2015-11-06 03:47 UTC
I am trying to connect MPD clients to mopidy (with spotify extension). 
Everytime I connect (using different clients), it crashes with a "Timeout: Operations did not complete in 10.000s. I can attach a log if needed. 

Without the spotify extension, all works. I can see local files, play them, etc.

Also, after the crash, when I control-c to exit mopidy, I get a bunch of "Exception AttributeError: '__exit__' in <built-in method gc_wref_remove of tuple object at 0x6f3689c0> ignored" messages.

Sorry if there is an obvious solution... I have tried everything that I can think of.

**Comment by jodal** [comment] 2015-11-09 23:13
Closing as duplicate of #71

**Closed by jodal** 2015-11-09 23:13 UTC
