### ISSUE TITLE
Search throws an exception

### ISSUE THREAD

**Issue by bartroff** [mopidy/mopidy-spotify#91] opened 2016-02-04 11:28 UTC
Hi there,

I suddenly ran into a problem when searching for songs on spotify. After startup of mopidy I am allowed to do one or two searches succesfully on spotify, afterwards it doesnt return any results and throws an exception in the log. I have been using it for a long time with no problems. Tried package upgrade, dist upgrade, reboot without any results:

Running Linux Ubuntu
Mopidy v. 1.1.2
Mopidy-spotify v. 2.2.0
Mopidy-soundcloud v. 2.0.2-1

Log output:

```
INFO     Searching Spotify for: "batman"
INFO     Searching SoundCloud for: batman
INFO     'Batman [Prod. By Tokyo Dre]' can't be streamed from SoundCloud
ERROR    SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 344, in search
    result = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/library.py", line 42, in search
    query, uris, exact)
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/search.py", line 44, in search
    sp_search.load()
  File "/usr/lib/python2.7/dist-packages/spotify/search.py", line 110, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/spotify/utils.py", line 242, in load
    _check_error(obj)
  File "/usr/lib/python2.7/dist-packages/spotify/utils.py", line 206, in _check_error
    error_type, ignores=[spotify.ErrorType.IS_LOADING])
  File "/usr/lib/python2.7/dist-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: General transient error
```
 
Any idea whats going on?

**Comment by trygveaa** [comment] 2016-02-04 11:40
Closing as duplicate of #89.

**Closed by trygveaa** 2016-02-04 11:40 UTC
