### ISSUE TITLE
Search fails with "General transient error"

### ISSUE THREAD

**Issue by timothylhuillier** [mopidy/mopidy-spotify#89] opened 2016-02-03 08:08 UTC
Sometimes when I start mopidy since today, I have this error :

    INFO     Logged in to Spotify in online mode
    INFO     Searching Spotify for: "worakls"
    ERROR    SpotifyBackend backend caused an exception.
    Traceback (most recent call last):
      File "/Users/tim/Documents/Sites/python/mopidy-dev/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
        yield
      File "/Users/tim/Documents/Sites/python/mopidy-dev/mopidy/mopidy/core/library.py", line 347, in search
        result = future.get()
      File "/usr/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
        compat.reraise(*self._data['exc_info'])
      File "/usr/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
        exec('raise tp, value, tb')
      File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
        response = self._handle_receive(message)
      File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
        return callee(*message['args'], **message['kwargs'])
      File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/library.py", line 42, in search
        query, uris, exact)
      File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/search.py", line 44, in search
        sp_search.load()
      File "/usr/local/lib/python2.7/site-packages/spotify/search.py", line 110, in load
        return utils.load(self._session, self, timeout=timeout)
      File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 242, in load
        _check_error(obj)
      File "/usr/local/lib/python2.7/site-packages/spotify/utils.py", line 206, in _check_error
        error_type, ignores=[spotify.ErrorType.IS_LOADING])
      File "/usr/local/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
        raise LibError(error_type)
    LibError: General transient error

And when I exit mopidy (^C) and restart more times, that oki. I don't understand why

Thanks

**Comment by relthyg** [comment] 2016-02-03 09:27
I can confirm this error, but only having flash disabled in the browser. It happens on searching. With flash enabled everything works fine.

**Comment by trygveaa** [comment] 2016-02-03 12:09
Hm, I also got this earlier today. And now I'm getting:

    ERROR    Spotify streaming error: <ErrorType.NO_STREAM_AVAILABLE: 18>

Not sure if it's related or not.

**Comment by albinekb** [comment] 2016-02-03 12:09
Can't play anything today! Getting same kind of errors

**Comment by kingosticks** [comment] 2016-02-03 12:20
https://twitter.com/SpotifyStatus/status/694855504930148352
> We’re investigating some issues and finding out more. Thanks for your reports - we’ll keep you updated here.

So the specific problems we see today are probably nothing to do with mopidy-spotify.

**Comment by timothylhuillier** [comment] 2016-02-03 12:21
Thanks @kingosticks

**Comment by adamcik** [comment] 2016-02-03 12:23
Wonder if we should catch these though and make it a warning or error log entry and then have a debug entry for the traceback? Though these might be hard to reproduce, so maybe better just to leave the traceback and just make sure to have a better error message?

**Comment by kingosticks** [comment] 2016-02-03 12:23
@timothylhuillier but your exception should be handled.

**Comment by kingosticks** [comment] 2016-02-03 12:44
And Spotify is working again for me now. See if you are still having issues @timothylhuillier

**Comment by timothylhuillier** [comment] 2016-02-03 13:24
I confirm, I have already this problem when I looking for artist but when I go to playlist : http://screencloud.net/v/wQFh in bottom, my spotify music start.

I develop my frontend app for sync my light so, I cancel and start mopidy every time. Before already oki but Since this morning I must reboot my computer that my search work.

I don't know why

**Comment by robin92** [comment] 2016-02-03 15:42
Affected as well since today.
```
Feb 03 16:27:19 gladius systemd[590]: Started Mopidy music server.
Feb 03 16:27:19 gladius mopidy[2215]: ** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy 1.1.2
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Loading config from builtin defaults
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Loading config from /home/robin/.config/mopidy/mopidy.conf
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Loading config from command line options
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Enabled extensions: spotify, mpd, softwaremixer, file
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Disabled extensions: local, m3u, http, stream
Feb 03 16:27:20 gladius mopidy[2215]: WARNING  Found local configuration errors, the extension has been automatically disabled:
Feb 03 16:27:20 gladius mopidy[2215]: WARNING    local/media_dir must be set.
Feb 03 16:27:20 gladius mopidy[2215]: WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy mixer: SoftwareMixer
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy audio
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy backends: FileBackend, SpotifyBackend
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Audio output set to "autoaudiosink"
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy core
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Logged in to Spotify in offline mode
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Starting Mopidy frontends: MpdFrontend
Feb 03 16:27:20 gladius mopidy[2215]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
Feb 03 16:27:20 gladius mopidy[2215]: INFO     Logged in to Spotify in online mode
Feb 03 16:27:21 gladius mopidy[2215]: INFO     New MPD connection from [::ffff:127.0.0.1]:47832
Feb 03 16:27:30 gladius mopidy[2215]: INFO     Searching Spotify for: artist:"Dream Theater"
Feb 03 16:27:30 gladius mopidy[2215]: ERROR    SpotifyBackend backend caused an exception.
Feb 03 16:27:30 gladius mopidy[2215]: Traceback (most recent call last):
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
Feb 03 16:27:30 gladius mopidy[2215]: yield
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 344, in search
Feb 03 16:27:30 gladius mopidy[2215]: result = future.get()
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
Feb 03 16:27:30 gladius mopidy[2215]: exec('raise exc_info[0], exc_info[1], exc_info[2]')
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
Feb 03 16:27:30 gladius mopidy[2215]: response = self._handle_receive(message)
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
Feb 03 16:27:30 gladius mopidy[2215]: return callee(*message['args'], **message['kwargs'])
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/mopidy_spotify/library.py", line 42, in search
Feb 03 16:27:30 gladius mopidy[2215]: query, uris, exact)
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/mopidy_spotify/search.py", line 44, in search
Feb 03 16:27:30 gladius mopidy[2215]: sp_search.load()
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/spotify/search.py", line 110, in load
Feb 03 16:27:30 gladius mopidy[2215]: return utils.load(self._session, self, timeout=timeout)
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 242, in load
Feb 03 16:27:30 gladius mopidy[2215]: _check_error(obj)
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 206, in _check_error
Feb 03 16:27:30 gladius mopidy[2215]: error_type, ignores=[spotify.ErrorType.IS_LOADING])
Feb 03 16:27:30 gladius mopidy[2215]: File "/usr/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
Feb 03 16:27:30 gladius mopidy[2215]: raise LibError(error_type)
Feb 03 16:27:30 gladius mopidy[2215]: LibError: General transient error
```

**Comment by trygveaa** [comment] 2016-02-04 11:42
Seems like there still are some issues, but Spotify doesn't report any issues on their twitter now.

**Comment by bartroff** [comment] 2016-02-04 12:01
It seems you are able to do a search right after mopidy starts and after that it breaks. Weird.

**Comment by kingosticks** [comment] 2016-02-04 12:35
Historically I don't think  'Transient' errors are something they ever report since they don't affect all users.

**Comment by Ticalie** [comment] 2016-02-04 14:23
The strange this is if you continue to retry the search, eventually a result will come back.
As a hacky fix I've created a loop that re-searches if it fails...
```
mopidy.library.search(uri).then(function (results) {
   if(results.length == 0) { //mopidy-spotify done gone broke
      //SearchAgain
   }
}
```
This usually completes within 10 tries.

**Comment by timothylhuillier** [comment] 2016-02-04 22:58
I don't modifed anything but now, it's rework ... lol

**Comment by connrs** [comment] 2016-02-11 13:00
I've been watching this thread for a few days, but didn't want to weigh in if I had nothing useful to say.

This issue only really appears to have impacted Spotify search; generally browsing for specific albums and artists seems to be working fine. The workaround at my office, has been to use browser history to find our favourites to add music to our play queue (our mopidy web client embeds the Spotify URI in to the URL (/#albums/spotify:album:44Ig8dzqOkvkGDzaUof9lK/Led%20Zeppelin/Led%20Zeppelin%20IV) as you browse, so we haven't been badly impacted.

One final note: The issue has gone from intermittent to continuous over the last 24 hours for me.

I'm not sure if I can do anything to help here as I know too little Python and have no experience with Spotify's APIs. If you need anything (even if it's just moral support!) please let me know.

**Comment by kingosticks** [comment] 2016-02-11 17:05
This is indeed affecting numerous people today, possibly everyone. I've asked Spotify for information but they have not responded. Note that the search at play.spotify.com is working fine so this issue is probably confined to whatever Spotify service endpoint libspotify searches use; there probably isn't anything we can do other than handle the exception better.

**Comment by liamhendricks** [comment] 2016-02-11 19:52
Still receiving this error today.

**Comment by adamcik** [comment] 2016-02-11 22:46
https://developer.spotify.com/web-api/migration-guide/ - so it turns out Spotify turned off their old metadata API, which it turns out libspotify used... So this is basically going to be broken until someone scrambles to get a workaround using the web apis in place :/

**Comment by d3rrial** [comment] 2016-02-12 15:55
The only client I currently have that works with this is mopify... mopidy springs the same error, but the results show up regardless.

**Comment by adamcik** [comment] 2016-02-13 20:46
For the record, the reason mopify still works is that it doesn't use mopidy for search or metadata lookup. It just uses the new web apis directly from your browser.

**Comment by jodal** [comment] 2016-02-14 14:07
Fixed in release-2.3 branch by using the Web API for search. Will be released soon.

Leaving the issue open until the fix has landed in the develop branch.

**Closed** 2016-02-14 21:14 UTC
Labels: bug

**Comment by jodal** [comment] 2016-02-14 21:15
Fixed in Mopidy-Spotify 2.3.1 which has just been released. Thanks to @trygveaa for making Mopidy-Spotify use the Spotify Web API for searching.

**Comment by johnedvard** [comment] 2016-02-15 07:25
Very good work with the fix. I was just wondering if the update is added to homebrew? I am still stuck with version 2.2.0. 
```
brew install mopidy/mopidy/mopidy-spotify
==> Installing mopidy-spotify from mopidy/mopidy
Error: mopidy-spotify-2.2.0 already installed
```
Maybe I am doing something wrong?

**Comment by dsdeiz** [comment] 2016-02-15 07:27
Mine is `2.3.1`. Maybe do a `brew update` first?

**Comment by bartroff** [comment] 2016-02-15 07:41
Works like a charm. Thanks!

**Comment by johnedvard** [comment] 2016-02-15 08:11
I had to do a `brew update` and then a `brew unlink mopidy-spotify`, and then install it again 
`brew install mopidy-spotify`. Thanks for the feedback :)
