### ISSUE TITLE
Tags (song metadata) not getting passed through audio output shout2send

### ISSUE THREAD

**Issue by allquixotic** [mopidy/mopidy-spotify#79] opened 2015-11-28 01:49 UTC
Using mopidy and mopidy-spotify "develop" branch, latest as of 11/27. Logs and configs: https://gist.github.com/allquixotic/be9ba751a8a690538f10

My audio pipeline is `lame ! shout2send ...` to an Icecast2 server.

When playing tracks from mopidy-Local (local filesystem MP3s), metadata tags are sent 100% fine and are received and processed on the client, so the client knows what tracks are playing. 

But, when the track playing is from Spotify, no metadata/tags are sent, and it shows as "Unknown" for the artist, track title, album, etc. in the client.

This leads me to conclude that mopidy-spotify is not sending tags properly or at all. But the logs above show that pyspotify2 is correctly detecting the metadata.

**Comment by adamcik** [comment] 2015-11-28 22:49
This should probably be solved in mopidy itself, inside the audio actor. Correct behaviour would be to postpone sending the metadata until the pipeline is in a "sane" state. Currently we are emitting this during `change_track` which is way to early.

**Comment by allquixotic** [comment] 2015-11-28 22:50
Tentative hack in mopidy core that "resolves" this issue (gently tested; it works when letting songs run to the end, or when skipping to another track, as well as with the initial playback):

```
diff --git a/mopidy/audio/actor.py b/mopidy/audio/actor.py
index b8b3d9a..def5adf 100644
--- a/mopidy/audio/actor.py
+++ b/mopidy/audio/actor.py
@@ -398,6 +398,7 @@ class Audio(pykka.ThreadingActor):
         self._playbin = None
         self._outputs = None
         self._about_to_finish_callback = None
+        self._pending_track = None
 
         self._handler = _Handler(self)
         self._appsrc = _Appsrc()
@@ -726,6 +727,9 @@ class Audio(pykka.ThreadingActor):
             logger.warning(
                 'Setting GStreamer state to %s failed', state.value_name)
             return False
+
+        if state == gst.STATE_PLAYING:
+            self.set_metadata(self._pending_track)
         # TODO: at this point we could already emit stopped event instead
         # of faking it in the message handling when result=OK
         return True
@@ -742,6 +746,10 @@ class Audio(pykka.ThreadingActor):
         :param track: the current track
         :type track: :class:`mopidy.models.Track`
         """
+        if track is None:
+            gst_logger.debug('Track is none')
+            return
+        self._pending_track = track
         taglist = gst.TagList()
         artists = [a for a in (track.artists or []) if a.name]
 
@@ -763,7 +771,7 @@ class Audio(pykka.ThreadingActor):
         event = gst.event_new_tag(taglist)
         # TODO: check if we get this back on our own bus?
         self._playbin.send_event(event)
-        gst_logger.debug('Sent tag event: track=%s', track.uri)
+        gst_logger.debug('Sent tag event: track=%s, artist=%s, name=%s, album=%s', track.uri, taglist[gst.TAG_ARTIST], track.name, track.album.name)
 
     def get_current_tags(self):
         """
```

**Comment by adamcik** [comment] 2015-11-29 15:18
We could also just consider emitting the metadata when the first buffer gets delivered. Should make this work correctly irrespective of fixes in mopidy itself.

**Comment by jodal** [comment] 2016-02-05 12:23
Closing as duplicate of mopidy/mopidy#1357.

**Closed by jodal** 2016-02-05 12:23 UTC
