### ISSUE TITLE
Search stopped working with ncmpcpp mpd client

### ISSUE THREAD

**Issue by Jorick** [mopidy/mopidy-spotify#93] opened 2016-02-11 16:36 UTC
I use ncmpcpp as a front end for mopidy and mopidy spotify. Lately I'm getting the following errors when searching for music:

```
ERROR    SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 344, in search
    result = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/library.py", line 42, in search
    query, uris, exact)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/search.py", line 44, in search
    sp_search.load()
  File "/usr/lib/python2.7/site-packages/spotify/search.py", line 110, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 242, in load
    _check_error(obj)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 206, in _check_error
    error_type, ignores=[spotify.ErrorType.IS_LOADING])
  File "/usr/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: General transient error
```

Strange thing is that sometimes search works but I can't trace down what exactly goes wrong and why.

When I use mopify as a front end, search works fine and I can play music without a problem.

versions: 
mopidy 1.1.2
mopidy-spotify 2.3.0

**Comment by kingosticks** [comment] 2016-02-11 16:47
This is a duplicate of the dubiously named issue at https://github.com/mopidy/mopidy-spotify/issues/89

**Comment by trygveaa** [comment] 2016-02-11 16:51
I renamed #89 since a couple of people has missed that. Closing this as a duplicate.

**Closed by trygveaa** 2016-02-11 16:51 UTC
