### ISSUE TITLE
Pauses other tracks when no connection to Spotify

### ISSUE THREAD

**Issue by DavisNT** [mopidy/mopidy-spotify#55] opened 2015-05-17 12:53 UTC
If internet connectivity is lost while playing Spotify tracks (or before trying to start a Spotify track) then Mopidy-Spotify starts to pause playback each few seconds (most likely each time when ` Spotify connection error: Cannot connect to Spotify` is being logged). 
This behavior continues when playing local files and only way to stop it is restart of Mopidy.

**Comment by jodal** [comment] 2015-05-18 09:47
I believe this is a duplicate of #1, which is fixed in the yet-to-be-released Mopidy-Spotify 2.0.

**Closed by jodal** 2015-05-18 09:47 UTC
