### ISSUE TITLE
SpotifyBackend does not implement library.search() with "exact" support.

### ISSUE THREAD

**Issue by cyda89** [mopidy/mopidy-spotify#316] opened 2021-08-26 17:10 UTC
I am running mopidy with mopidy-spotify on Raspbian (RasPi 4). When using the search from [Mopidy Webclient](https://pypi.org/project/Mopidy-MusicBox-Webclient/) I do not get any results, but the terminal shows following warning:
WARNING  2021-08-26 18:38:32,275 [5356:Core-9] mopidy.core.library
  SpotifyBackend does not implement library.search() with "exact" support. Please upgrade it.

My config: 
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
#config_dir = $XDG_CONFIG_DIR/mopidy
#data_dir = $XDG_DATA_DIR/mopidy
#max_tracklist_length = 10000
#restore_state = false

[logging]
#color = true
#console_format = %(levelname)-8s %(message)s
#debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
#debug_file = mopidy.log
#config_file =

[audio]
#mixer = software
#mixer_volume = 
output = alsasink 
#buffer_time = 

[proxy]
#scheme = 
#hostname = 
#port = 
#username = 
#password = 

[mpd]
#enabled = true
#hostname = 127.0.0.1
#port = 6600
#password = 
#max_connections = 20
#connection_timeout = 60
#zeroconf = Mopidy MPD server on $hostname
#command_blacklist = 
#listall
#listallinfo
#default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
#static_dir =
#zeroconf = Mopidy HTTP server on $hostname
#allowed_origins = 
#csrf_protection = true

[m3u]
#enabled = true
#base_dir = $XDG_MUSIC_DIR
#default_encoding = latin-1
#default_extension = .m3u8
#playlists_dir =

[softwaremixer]
#enabled = true

[local]
#enabled = true
#library = json
#media_dir = $XDG_MUSIC_DIR
#scan_timeout = 1000
#scan_flush_threshold = 100
#scan_follow_symlinks = false
#excluded_file_extensions = 

[spotify]
client_id = secret
client_secret = secret
username = secret
password = secret

[musicbox_webclient]
enabled = true
musicbox = false
#websocket_host =
#websocket_port =
on_track_click = PLAY_ALL`

I can't tell if it's a problem with mopidy-spotify or the cause is in the webclient.
Either way, any help is very welcome

Edit: removed some parts of the for readabilities sake. (Only parts that were commented out anyways)

**Comment by kingosticks** [comment] 2022-01-12 12:55
Sorry for the long delay in responding. We added this support [7 years ago](https://github.com/mopidy/mopidy-spotify/commit/3974ce78844ed1525711002ad47dc0c4b98df866) so I think this warning message must be a redherring. Could you reproduce this with a verbose log? Or provide the search you did so I might try and reproduce.

**Comment by kingosticks** [comment] 2022-01-12 23:56
This might have been due to https://github.com/mopidy/mopidy-spotify/issues/280 and fixed in https://github.com/mopidy/mopidy-spotify/pull/325. Reopen if this a problem.

**Closed by kingosticks** 2022-01-12 23:56 UTC
