### ISSUE TITLE
No longer seeing any Spotify Playlists

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy-spotify#27] opened 2014-10-27 19:15 UTC
As of this evening, I am no longer seeing any Spotify playlists being loaded by mopidy. I've changed nothing on my installation, as far as I recall - and it's happening on 2 systems - so it must be something at Spotify. All my playlists are still there in the official client, and mopidy will search for and play spotify tracks.

Have Spotify mangled their API again so this no longer works?

**Comment by jodal** [comment] 2015-01-20 16:04
I've still never experienced this issue myself, no new instances of the issue has been reported since November, there is no clear way to reproduce the issue, and AFAIK it has never been observed when using Mopidy-Spotify 2. Not much I can do here, thus closing.

**Closed by jodal** 2015-01-20 16:04 UTC
Labels: bug

**Comment by jaedb** [comment] 2015-02-14 19:32
Hi @jodal I'm experiencing this issue, but would like to upgrade to Mopidy-Spotify 2 to see if this fixes it. When is Mopidy-Spotify 2 due to be released to pypi?

**Comment by jodal** [comment] 2015-02-16 21:40
@jaedb Working on it! Any day now :-)

**Comment by berrydejager** [comment] 2016-09-25 21:46
Still valid, i used a combination of the Fatg3erman solution with some extra sauces over it; [http://virtual.berrydejager.com/pimusicbox-not-showing-spotify-playlist-fixed/](http://virtual.berrydejager.com/pimusicbox-not-showing-spotify-playlist-fixed/)

**Comment by kingosticks** [comment] 2016-09-25 21:53
That's for an old version of mopidy-spotify. This is not an issue in the latest version.

**Comment by berrydejager** [comment] 2016-09-25 22:09
Thanks for the quick response! So PiMusicBox need to move over to the new mopidy-spotify version ;-)

**Comment by kingosticks** [comment] 2016-09-26 06:52
Yes.
